### ISSUE TITLE
sudo cp ./contrib/U6143_ssd1306.service /etc/systemd/system/ fails

### ISSUE THREAD

**Issue by scyto** [darkgrue/U6143_ssd1306#2]
i followed the instructions exactly

when i  execute `sudo cp ./contrib/U6143_ssd1306.service /etc/systemd/system/` i get an error
instructions need to be `sudo cp ../contrib/U6143_ssd1306.service /etc/systemd/system/`

or you need to tell folks to cd backup one level (i know this seems basic, but not everyone is used to compiling stuff) only took me 5 mins to figure out, might help someone else....

**Comment by darkgrue** [comment]
Won't fix. There's no instruction to be in the `contrib/` directory, which your instructions presume. The original instructions are built on the presumption you start and end in the directory you issued the `make` command from.
